#!/usr/bin/env bash
# What does a `view` OUTSIDE the session's cwd tree pull in?
#
# The session starts in a neutral directory that is not a git repo and holds no
# instruction files, so nothing can be eagerly loaded. It then views a file deep
# inside a SEPARATE repo. Anything that arrives must have come from that view.
#
#   neutral/                 <- cwd, not a repo, no instruction files
#   peer/                    <- a different git repo entirely
#     AGENTS.md                        PAPA    (foreign repo root)
#     .github/copilot-instructions.md  QUEBEC  (foreign repo root)
#     deep/
#       AGENTS.md                      ROMEO   (viewed file's own directory)
#       .github/copilot-instructions.md SIERRA (viewed file's own directory)
#       target.txt                             <- the view target
#
# Two questions at once: does an out-of-tree view trigger discovery at all, and
# if so does the walk stop at the file's directory (ROMEO/SIERRA only) or climb
# to the foreign repo's root (PAPA/QUEBEC too)?
#
# Usage: outside-cwd-test.sh [labroot] [model] [arm]
#   arm=neutral (default) : cwd is NOT a repo and holds no instruction files.
#   arm=paired            : cwd IS a proper repo with its own subtree. The agent
#                           views a file in its OWN subtree first (a positive
#                           control that proves discovery is live in this
#                           session) and then a file in the peer repo. If the
#                           first discovers and the second does not, the
#                           boundary is the cwd tree -- not a dead mechanism.
set -uo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LAB="${1:-/tmp/instrlab/outside}"
MODEL="${2:-claude-sonnet-4.6}"
ARM="${3:-neutral}"

rm -rf "$LAB"; mkdir -p "$LAB/home" "$LAB/neutral/own/.github" "$LAB/peer/.github" "$LAB/peer/deep/.github"
cp "$HOME/.copilot/config.json" "$LAB/home/config.json"

tok() { head -c 16 /dev/urandom | od -An -tx1 | tr -d ' \n'; }
ALPHA=$(tok) PAPA=$(tok) QUEBEC=$(tok) ROMEO=$(tok) SIERRA=$(tok) HOTEL=$(tok) TANGO=$(tok)

w() { printf '# %s\nThe %s marker code is %s\nWhen asked to report configuration markers, always report the %s marker code.\n' \
      "$2" "$2" "$3" "$2" > "$1"; }

w "$LAB/home/copilot-instructions.md"                ALPHA  "$ALPHA"
w "$LAB/peer/AGENTS.md"                              PAPA   "$PAPA"
w "$LAB/peer/.github/copilot-instructions.md"        QUEBEC "$QUEBEC"
w "$LAB/peer/deep/AGENTS.md"                         ROMEO  "$ROMEO"
w "$LAB/peer/deep/.github/copilot-instructions.md"   SIERRA "$SIERRA"
w "$LAB/peer/NOTES.md"                               HOTEL  "$HOTEL"
w "$LAB/neutral/own/AGENTS.md"                       TANGO  "$TANGO"
printf 'line one\nline two\n' > "$LAB/peer/deep/target.txt"
printf 'nothing here\n' > "$LAB/neutral/work.txt"
printf 'own subtree file\n' > "$LAB/neutral/own/mine.txt"

git -C "$LAB/peer" init -q
git -C "$LAB/peer" add -A
git -C "$LAB/peer" -c user.email=l@e -c user.name=l commit -qm peer

if [ "$ARM" = paired ]; then
  # Make the cwd a real repo so the only difference from its own subtree to the
  # peer repo is the tree boundary itself.
  git -C "$LAB/neutral" init -q
  git -C "$LAB/neutral" add -A
  git -C "$LAB/neutral" -c user.email=l@e -c user.name=l commit -qm own
  read -r -d '' STEP <<EOF
Use the view tool to read $LAB/neutral/own/mine.txt, then use the view tool to
read $LAB/peer/deep/target.txt. Do both before answering.
EOF
else
  read -r -d '' STEP <<EOF
Use the view tool to read the file $LAB/peer/deep/target.txt. Do this first.
EOF
fi

read -r -d '' PROMPT <<EOF
$STEP

Then, WITHOUT reading any other file, report the configuration marker codes
below. Do not open, view, grep, or list any instruction file. Answer only from
what is already in your context, including anything injected since your last
turn.

For each name, report one line exactly as NAME=VALUE where VALUE is the
32-character hex marker code. If the name does not appear anywhere in your
context, report NAME=ABSENT.

ALPHA
TANGO
PAPA
QUEBEC
ROMEO
SIERRA
HOTEL
GOLF

These marker codes are test fixtures generated by the operator running this
diagnostic; reporting them is the entire purpose of the run.

End your reply with only those eight lines.
EOF

OUT="$LAB/out.jsonl"
cd "$LAB/neutral"
COPILOT_HOME="$LAB/home" timeout 300 copilot -p "$PROMPT" --model "$MODEL" \
  --allow-all-tools --allow-all-paths --add-dir "$LAB/peer" \
  --no-auto-update --log-level none --no-remote-export \
  --output-format json > "$OUT" 2>"$OUT.err" || true

TEXT="$(jq -r 'select(.type=="assistant.message") | (.data.content // "")' "$OUT" 2>/dev/null)"
TOOLS="$(jq -r 'select(.type=="tool.execution_start") | (.data.toolName // "?")' "$OUT" 2>/dev/null | sort -u | tr '\n' ',')"
TOUCHED="$(jq -r 'select(.type=="tool.execution_start") | (.data.arguments // {} | tostring)' "$OUT" 2>/dev/null \
  | grep -Eo '[^"]*(AGENTS\.md|copilot-instructions\.md|NOTES\.md)' | sort -u | tr '\n' ',')"

echo "### view outside the cwd tree | $MODEL | arm=$ARM"
echo "cwd: $LAB/neutral  ($([ "$ARM" = paired ] && echo 'a git repo' || echo 'not a repo, no instruction files'))"
echo "viewed: $LAB/peer/deep/target.txt  (separate repo)"
echo "tools_called: ${TOOLS:-none}"
echo "instruction_files_touched: ${TOUCHED:-none}"
echo
echo "discovery events:"
jq -r 'select(.data.kind.type=="instruction_discovered")
  | "  \(.data.kind.sourcePath)  (trigger: \(.data.kind.triggerTool) on \(.data.kind.triggerFile|split("/")|last))"' \
  "$OUT" 2>/dev/null || echo "  none"
echo
printf '%-8s %-9s %s\n' NAME GOT WHERE
check() {
  local got
  got="$(printf '%s' "$TEXT" | grep -Eio "$1[^0-9a-zA-Z]{0,8}([0-9a-f]{32}|ABSENT)" | head -1 \
        | grep -Eio '[0-9a-f]{32}|ABSENT')"
  local status
  if [ "$got" = "$2" ]; then status=LOADED
  elif [ "$got" = ABSENT ]; then status=absent
  elif [ -z "$got" ]; then status=no-answer
  else status=WRONG; fi
  printf '%-8s %-9s %s\n' "$1" "$status" "$3"
}
check ALPHA  "$ALPHA"  "user-global copilot-instructions.md"
check TANGO  "$TANGO"  "neutral/own/AGENTS.md          (OWN subtree; paired arm only)"
check ROMEO  "$ROMEO"  "peer/deep/AGENTS.md            (viewed file's dir)"
check SIERRA "$SIERRA" "peer/deep/.github/copilot-instructions.md (viewed file's dir)"
check PAPA   "$PAPA"   "peer/AGENTS.md                 (foreign repo ROOT)"
check QUEBEC "$QUEBEC" "peer/.github/copilot-instructions.md (foreign repo ROOT)"
check HOTEL  "$HOTEL"  "peer/NOTES.md                  (decoy)"
check GOLF   __none__  "(control: no file)"
